config/routes.rb
Gurupu::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/login" => "sessions#index"
  resources :groups do
    patch :state_change, on: :member
    patch :quit, on: :member
    resource :state, only: [:create, :delete]
    resources :users, only: [:index, :new, :create, :destroy] do
      member do
        patch :confirm
        patch 'become-owner'=> 'users#become_owner', as: 'become_owner'
        patch 'become-member'=> 'users#become_member', as: 'become_member'
      end
      collection do
        post 'invite-member'=> 'users#invite', as: 'invite_member'
        post 'invite-by-email'=> 'invitations#create', as: 'invite_by_meail'
        patch :accept
      end
    end
    resources :tags, except: [:index]
    resources :expenses do
      collection do
        get :summary
        get :export
      end
    end
  end
  resources :invitations, only: [:accept, :show] do
    patch :accept, on: :member
  end
  get "users/typeahead"

  get "welcome/newbie"
  root :to => 'welcome#index'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text(255)
#  slug        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  state       :string(255)
#

class Group < ActiveRecord::Base
  include Slugable
  extend Enumerize
  validates :name, presence: true, length: { in: 5..20 }
  validates :description, presence: true, length: { maximum: 255 }

  has_many :expenses
  has_many :group_tags
  has_many :tags, through: :group_tags
  has_many :group_users
  has_many :members, through: :group_users, source: :user
  has_many :owners,  -> { where("group_users.role = 'admin'") },  through: :group_users, source: :user
  STATE = [:active, :frozen, :trashed]
  enumerize :state, in: STATE, predicates: true, default: :active

  def add_owner(user)
    group_users.create(user: user, role: 'admin', state: 'join')
  end

  def editable_by?(user)
  end

  def change_state(state)
    self[:state] = state
    self.save    
  end

  def add_owner(user)
    gu = self.group_users.build(user: user, role: :admin, state: :join)
    gu.save
  end

  def add_member(user)
    gu = self.group_users.build(user: user, role: :member, state: :join)
    gu.save
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  prepend_before_action :set_group, except: [:new, :create]
  before_action :select_tag, only: [:new, :create, :edit, :update]
  before_action :tmp_tag, only: [:create, :update]

  def index
    @groups = current_user.groups
  end

  def state_change
    if @group.change_state(params[:state])
    else
      flash[:error] = 'Status change fail !!'
    end
    redirect_to edit_group_path
  end

  def quit
    trashed = (@group.group_users.where(state:"join").size==1)
    if (!trashed) && (current_user.is_owner_of?(@group)) && (@group.owners.size == 1)
      flash[:error] = "您是本團唯一的管理員，需指派繼任管理員才可退出團體"
      redirect_to :back
      return
    end
    msg=""
    if trashed
      @group.change_state('trashed')
      GroupUser.where("group_id = ?", @group.id).delete_all
      GroupTag.where("group_id = ?", @group.id).delete_all
      msg="and drop "
    end
    current_user.quit!(@group)

    flash[:notice] = "Quit "+msg+@group.name+" success"
    redirect_to groups_path
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.state = 'active'
    if @group.save
      @group.add_owner(current_user)
      (params[:tag_ids] || []).each { |i| @group.tags << Tag.find(i) }

      flash[:notice] = "Create Group success"
      redirect_to edit_group_path(@group)
    else
      render action: 'new'
    end
  end

  def edit
  end

  def show
    unless current_user.is_member_of?(@group)
      redirect_to new_group_user_path(@group)
    end
  end

  def update
    if @group.update(group_params)
      #----------------------------------------
      # group tags maintain
      # if expenses exist, cannot remove tag
      #----------------------------------------
      msg=''
      @sel_tag.each do |tag_id, tag_name, pre_check, final_check|
        tag=Tag.find(tag_id)
        if (pre_check.blank?)==true && (final_check.blank?)==false
          @group.tags << tag
        elsif (pre_check.blank?)==false && (final_check.blank?)==true
          if @group.expenses.active.find_by_tag_id(tag.id)
            msg=msg+' '+tag_name
          else
            @group.tags.delete(tag)
          end
        end
      end

      if msg==''
        flash[:notice] = "Update Group success"
      else
        flash[:error] = "cannot remove tag:"+msg
      end
      redirect_to edit_group_path
    else
      render action: 'edit'
    end
  end

  def invite
   GroupMailer.invite(current_user, @group,params[:mailto]).deliver
   redirect_to edit_group_path, :notice => "mailed:" + params[:mailto]
  end

  private
  def select_tag
    group_sel_tag = Tag.all.where(is_default: true)
    if @group != nil
      group_sel_tag += @group.tags.where(is_default: false)
    end
    @sel_tag=[]
    group_sel_tag.each do |tag|
      if @group != nil
        pre_check = @group.tags.include?(tag)
      else
        pre_check = false
      end
      @sel_tag<<[tag.id, tag.name, pre_check, pre_check]
    end
  end

  def tmp_tag
    tmp_tag=[]
    @sel_tag.each do |tag_id, tag_name, pre_check, final_check|
      tmp_tag<<[tag_id, tag_name, pre_check, (params[:tag_ids] || []).include?(tag_id.to_s)]
    end
    @sel_tag=tmp_tag
  end

  def set_group
    @group = Group.find_by_slug(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description)
  end

end


app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for @group, html: {class: "form-horizontal form-inline"} do |g| %>  
  <%= g.input :name,input_html: {class: "span5"},label: "團體名稱" %>  
  <%= g.input :description,input_html: {class: "span5", rows: "5"}, label: "簡述" %>  

  <div class="control-group">
  <label class="control-label">
    帳目支出分類
  </label>
  <div class="controls">  
  <div class="row">
  <div class="span4">
  <div class="row">
  <font size="3">  
    <% @sel_tag.each do |tag_id, tag_name, pre_check, final_check| %>          
      <div class="span2">
      <%= check_box_tag 'tag_ids[]', tag_id, final_check%>
      <%= tag_name %>      
      </div>      
    <% end %> 
  </font>
  </div>
  </div>
  </div>
  </div>  
  </div>    

  <%= link_to "　取消　", :back, class: "btn offset2"%>
  &nbsp &nbsp
  <% if controller.action_name == "new" ||
        controller.action_name == "create" %>        
    <%= g.button :submit ,"　建立　", class: "btn-info" %>
  <% else %>      
    <%= g.button :submit ,"　修改　", class: "btn-info" %>
  <% end %>      
<% end %>

<!--New Tag-->
<% if controller.action_name != "new" &&
      controller.action_name != "create" %>
  <%= simple_form_for Tag.new,
      html: {class: "form-horizontal form-inline"}, 
      url: group_tags_path(@group),
      method: :post do |t| %>
    <div class="control-group">
    <div class="controls">   
      <%= t.input_field :name, input_html: {class: "span3"}, label: "", placeholder:"輸入自訂分類" %>
      <%= image_submit_tag("add.png") %>
    </div>
    </div>  
  <% end %>
<% end %>




app/views/groups/edit.html.erb
<div class="row">
  <div class="span8">
    <%= render 'shared/group_header' %>

		<% gp_status = { active: "開放報帳", frozen: "凍結報帳" } %>
		<% gp_status = gp_status.with_indifferent_access %>

		<% if @group.group_users.find_by_user_id(current_user.id).join? %>

			<% is_owner=current_user.is_owner_of?(@group) %>

			<!--for owner-->
			<% if is_owner %>
				<%= render 'form' %>
			<% end %>

			<!--for member-->
			<% if !is_owner %>
				<font size="3"> 
				<dl class="dl-horizontal">
				  <dt>團體名稱</dt>
				  <dd><%= @group.name %></dd>
				  <br>

				  <dt>簡述</dt>
				  <dd><%= simple_format(@group.description) %></dd>
					<br>

					<dt>團體狀態</dt>
				  <dd><%= gp_status[@group.state] %></dd>
				  <br>  
				</dl>
				</font>
			<% end %>

			<!--chaneg group state-->
			<% if is_owner %>
				<table border="1" width="85%" style="border-color:orange" 
				class="offset1 table-bordered">
				  <tr>
				  	<th width="15%" style="color:white" bgcolor=orange>變更狀態</th>	  	
				  	<% @group.active? %> <!--for gem enumerize bug-->
				  	<% if @group.frozen? %>
					    <td style="font-size:11pt">目前狀態為凍結報帳，點擊開放報帳可恢復報帳功能
								<%= link_to '開放報帳', state_change_group_path(state: "active"), method: :patch, class: 'btn btn-success pull-right' %>			    
					    </td>     
					  <% else %>
					    <td style="font-size:11pt">注意，將狀態更改為凍結報帳後所有團員將無法報帳!
								<%= link_to '凍結報帳', state_change_group_path(state: "frozen"), method: :patch, class: 'btn btn-warning pull-right' %>	
					    </td>  	    
				    <% end %>
				  </tr>
				</table>
				<br>
			<% end %>

			<!--quit group-->
			<table border="1" width="85%" style="border-color:firebrick" class="offset1 table-bordered">
			  <tr>
			    <th width="15%" style="color:white" bgcolor=firebrick>退出團體</th>      
			    <td style="font-size:11pt">注意，退出團體後無法自行重新加入!
						<%if @group.group_users.where(state:"join").size==1 %>
			        <% msg='您是本團體最後一位成員，確認退團後此團體將被刪除，是否退出?' %>
						<% else %>
							<% msg='是否確定退團?' %>
						<% end %>
						<%= link_to '確認退出', quit_group_path, method: :patch, class: 'btn btn-danger pull-right', confirm: msg %>
			    </td>     
			  </tr>
			</table>
			<br>

		<% end %>

  </div>
  <%= render 'shared/groups_sidebar' %>
</div>

app/views/groups/index.html.erb
<!-- user not join any group yet -->
<% if @groups.count==0 %>
  <%= link_to(new_group_path, :class => "btn btn-info btn-large" ) do  %>
    建立新團
  <% end %>
<!-- user had groups -->
<% else %>
  <h3>
    <font color="palevioletred">
      參加的團體
    </font>
  <h3>

  <table class="table table-hover" width:100%>
    <thead>
      <tr>
        <th>團名</th>
        <th>敘述</th>
        <th>瀏覽</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |g| %>
        <tr>
          <td><%= g.name %></td>
          <td><%= g.description %></td>
          <td><%= link_to 'Link', group_expenses_path(g.slug) %>
          </td>
          <td>
            <% if g.owners.include?(current_user) %>
              <%= link_to "管理", edit_group_path(g.slug) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to(new_group_path, :class => "btn btn-info" ) do  %>
    建立新團
  <% end %>
<% end %>



app/views/groups/new.html.erb
<h2>建立新團</h2>
<hr />
<%= render 'form' %>