config/routes.rb
Gurupu::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/login" => "sessions#index"
  resources :groups do
    patch :state_change, on: :member
    patch :quit, on: :member
    resource :state, only: [:create, :delete]
    resources :users, only: [:index, :new, :create, :destroy] do
      member do
        patch :confirm
        patch 'become-owner'=> 'users#become_owner', as: 'become_owner'
        patch 'become-member'=> 'users#become_member', as: 'become_member'
      end
      collection do
        post 'invite-member'=> 'users#invite', as: 'invite_member'
        post 'invite-by-email'=> 'invitations#create', as: 'invite_by_meail'
        patch :accept
      end
    end
    resources :tags, except: [:index]
    resources :expenses do
      collection do
        get :summary
        get :export
      end
    end
  end
  resources :invitations, only: [:accept, :show] do
    patch :accept, on: :member
  end
  get "users/typeahead"

  get "welcome/newbie"
  root :to => 'welcome#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  provider   :string(255)
#  uid        :string(255)
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
    end
  end

  validates :provider,  presence: true
  validates :name,      presence: true
  validates :uid,       presence: true, uniqueness: true
  validates :email,     presence: true, uniqueness: true

  has_many :group_users
  has_many :groups, through: :group_users

  def join!(group)
    groups << group
  end

  def quit!(group)
    groups.delete(group)
  end

  def is_member_of?(group)
    gp = group_user(group)
    gp && gp.state.join?
  end

  def is_owner_of?(group)
    group_user(group).role.admin?
  end

  def is_waiting?(group)
    group_user(group).state.wait?
  end

  def is_inviting?(group)
    group_user(group).state.invite?
  end

  private
  def group_user(group)
    group_users.find_by(group: group)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_group, except: [:typeahead]
  before_action :check_group_status, except: [:typeahead]
  before_action :set_user, only: [:update, :destroy, :confirm]
  before_action :set_group_user, only: [:become_owner, :become_member, :confirm]
  before_action :check_permission, only: [:destroy, :confirm]

  def index
    @is_owner = current_user.is_owner_of?(@group)
  end

  def new
    @join_group_path = accept_group_users_path(@group)
  end

  def create
    group_user = current_user.group_users.build(group: @group,
      role: :member, state: :wait)
    group_user.save
    redirect_to group_expenses_path(@group)
  end

  def become_owner
    if @group_user.update(role: :admin)
      flash[:notice] = 'Successful update'
    else
      flash[:error] = 'Fail'
    end
    redirect_to group_users_path(@group_user.group)
  end

  def become_member
    if @group_user.user_id == current_user.id && @group_user.role.admin?
      if @group.owners.size == 1
        flash[:error] = '你是唯一的管理員'
      else
        @group_user.role = :member
        if @group_user.save
          flash[:notice] = 'Successful update'
        else
          flash[:error] = 'Fail'
        end
      end
    end
    redirect_to group_users_path(@group_user.group)
  end

  def confirm
    if @group_user.state.wait?
      @group_user.state = :join
    end
    if @group_user.save
      flash.now[:notice] = 'Successful update'
    else
      flash.now[:error] = 'Fail'
    end
    redirect_to group_users_path(@group_user.group)
  end

  def invite
    user = User.find_by(uid: params[:uid])
    unless user
      redirect_to group_users_path(@group), error: 'fail'
      return
    end
    group_user = GroupUser.new(user: user, group: @group,
      role: :member, state: :invite)
    if group_user.save
      flash[:notice] = 'Successful invite'
    else
      flash[:error] = 'Error'
    end
    redirect_to group_users_path(@group)
  end

  def accept
    group_user = GroupUser.find_by(group: @group, user: current_user)
    group_user.state = :join
    if group_user.save
      flash.now[:notice] = 'Successful join'
    else
      flash.now[:error] = 'Fail'
    end
    redirect_to group_path(@group)
  end

  def destroy
    if @user.is_owner_of?(@group)
      redirect_to @group, error: 'Permission denied'
    else
      @group.members.delete(@user)
      redirect_to group_users_path(@group)
    end
  end

  def typeahead
    result = User.select(:uid, :name).
      where("lower(name) like ?", "#{params[:name].downcase}%").to_a
    render json: result.to_json(only: [:uid, :name])
  end

  private
  def set_group
    @group = Group.find_by_slug(params[:group_id])
  end

  def check_group_status
    if @group.state.trashed?
      flash[:error] = 'This group is deleted'
      redirect_to groups_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_group_user
    @group_user = GroupUser.find_by(group: set_group, user_id: params[:id])
  end

  def check_permission
    if current_user == nil || !current_user.is_owner_of?(@group)
      flash[:error] = 'Permission denied'
      redirect_to @group
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
  <div class="span8">
    <%= render 'shared/group_header' %>
  <% if @is_owner %>
    <div class="invite-block">
    <%= form_tag invite_member_group_users_path(@group), id: 'invite-form' do |f| %>
      <span>邀請團員：</span>
      <%= select_tag 'member-type', options_for_select({'會員'=> 'member', '非會員'=>'email'}), class: 'input-small' %>
      <%= text_field_tag 'member', nil, autocomplete: 'off',
      placeholder: '輸入會員名稱' %>
      <%= text_field_tag 'email', nil, class: 'hidden', placeholder: '輸入Email' %>
      <%= hidden_field_tag 'uid' %>
      <%= submit_tag '確認', class: 'btn btn-primary' %>
    <% end %>
    </div>
  <% end %>
  <% if @group.members.any? %>
    <table class="table">
    <% @group.members.each do |member| %>
      <tr>
        <td><%= avatar_for(member) %>&nbsp;<%= member.name %></td>
        <td>
          <% case %>
          <% when member.is_owner_of?(@group) %>
            <%= '管理員' %>
          <% when member.is_waiting?(@group) %>
            <%= '待審核' %>
          <% when member.is_inviting?(@group) %>
            <%= '待加入' %>
          <% end %>
        </td>
        <td>
        <% if @is_owner %>
          <% case %>
          <% when member.id == current_user.id %>
            <%= link_to '退出管理員', become_member_group_user_path(@group, member),
              method: :patch, class: 'btn', confirm: '確定退出管理員?' %>
          <% when member.is_waiting?(@group) %>
            <%= link_to '接受', confirm_group_user_path(@group, member),
            method: :patch, class: 'btn', confirm: '確定接受入團申請?' %>
          <% when !member.is_owner_of?(@group) & member.is_member_of?(@group) %>
            <%= link_to '指定為管理員', become_owner_group_user_path(@group, member),
              method: :patch, class: 'btn', confirm: '確定指定此使用者為管理員?' %>
          <% end %>
        <% end %>
        </td>
        <td>
        <% if @is_owner && !member.is_owner_of?(@group) %>
          <%= link_to '刪除', [@group, member], method: :delete,
            class: 'btn btn-danger', confirm: '確定刪除此團員?' %>
        <% end %>
        </td>
        <td>
      </tr>
    <% end %>
    </table>
  <% end %>
  </div>
  <%= render 'shared/groups_sidebar' %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="span8">
    <h2><%= @group.name %></h2>
    <hr />
    <p><%= simple_format @group.description %></p>
    <%= link_to '確認入團', @join_group_path, method: :patch, class: 'btn btn-primary' %>
  </div>
  <%= render 'shared/groups_sidebar' %>
</div>