config/routes.rb
Gurupu::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/login" => "sessions#index"
  resources :groups do
    patch :state_change, on: :member
    patch :quit, on: :member
    resource :state, only: [:create, :delete]
    resources :users, only: [:index, :new, :create, :destroy] do
      member do
        patch :confirm
        patch 'become-owner'=> 'users#become_owner', as: 'become_owner'
        patch 'become-member'=> 'users#become_member', as: 'become_member'
      end
      collection do
        post 'invite-member'=> 'users#invite', as: 'invite_member'
        post 'invite-by-email'=> 'invitations#create', as: 'invite_by_meail'
        patch :accept
      end
    end
    resources :tags, except: [:index]
    resources :expenses do
      collection do
        get :summary
        get :export
      end
    end
  end
  resources :invitations, only: [:accept, :show] do
    patch :accept, on: :member
  end
  get "users/typeahead"

  get "welcome/newbie"
  root :to => 'welcome#index'

end

app/views/shared/_group_header.html.erb
<div class="group-header clearfix">
  <h2 class="pull-left"><%= @group.name %></h2>
  <%= render_list class: 'nav nav-tabs pull-right' do |li|
    li << link_to('帳目一覽', group_expenses_path(@group))
    li << link_to('瀏覽報表', summary_group_expenses_path(@group))
    li << link_to('團員名單', group_users_path(@group))
    li << link_to('設定', edit_group_path(@group))
  end %>
</div>


app/views/shared/_groups_sidebar.html.erb
<div class="span4">
  <div class="groups-sidebar">
    <%= link_to '建立新團體', new_group_path, class: 'btn btn-primary' %>
  <% if current_user.groups.any? %>
    <ul>
    <% current_user.groups.each do |group| %>
      <li class="clearfix">
        <span class="group-name"><%= group.name %></span>
        <span class="group-link pull-right"><%= link_to '瀏覽', group_path(group), class: 'btn' %></span>
      </li>
    <% end %>
    </ul>
  <% end %>
  </div>
</div>